name: Prerelease

on:
  release:
    types: [published]

jobs:
  build-and-push:
    # Remove runs-on, as soon as workflow expansion is supported by codeberg
    runs-on: ubuntu-24.04
    name: Build and push rc
    uses: ./.github/workflows/build-and-push.yml
    with:
      channel: rc
      versions: ${{ github.event.release.tag_name }}
    secrets: inherit
